Sg/asreview
UtrechtUniversity/researchcloud-items pull request #6
Opened 2022-03-23 10:18 UTC by SytseGroenwold

My first pull request! 
I have (and for a little while will) include you both as reviewer, because 6 see more than 4, right?
Jelle and I have tested the functionality of the workspace you can create with this, and it works fine. Multi-user support is not present in ASReview yet and the things Jelle and I have tried did not lead to a successful result, so the plugin will remain for a single-user workspace.

2022-03-24 15:29 UTC, tsmeele requested changes
see comments

2022-03-25 12:13 UTC, J535D165 reviewed
Nice! Some small textual/branding suggestions.

2022-03-25 12:13 UTC, J535D165 commented on docs/playbooks/asreview.md
> +Automatic Systematic Review (ASReview) is an application that uses active machine learning to facilitate and predict relevancy of papers during a systematic review process.
```suggestion
ASReview LAB is an application that uses active learning to facilitate and predict the relevancy of papers during a systematic review.
```

2022-03-25 12:13 UTC, J535D165 commented on docs/roles/asreview.md
> +Automatic Systematic Review (ASReview) is an application that uses active machine learning to facilitate and predict relevancy of papers during a systematic review process.
```suggestion
ASReview LAB is an application that uses active learning to facilitate and predict the relevancy of papers during a systematic review.
```

2022-03-25 12:13 UTC, J535D165 commented on docs/roles/asreview.md
> +This role installs ASReview through pip, as recommended by the documentation.
```suggestion
This role installs ASReview LAB through pip, as recommended by the documentation.
```

2022-03-25 12:13 UTC, J535D165 commented on docs/roles/asreview.md
> +For more information, visit the [official website](https://asreview.nl/).
```suggestion
For more information, visit https://asreview.ai/.
```

2022-03-25 12:13 UTC, J535D165 commented on roles/asreview/tasks/main.yml
> +- name: Install ASReview through pip
```suggestion
- name: Install ASReview LAB through pip
```

2022-03-25 12:13 UTC, J535D165 commented on asreview.yml
> +- name: Install ASReview system-wide
```suggestion
- name: Install ASReview LAB system-wide
```

2022-03-31 14:06 UTC, tsmeele commented on docs/playbooks/asreview.md
> +# Playbook <name>
pls add name

2022-03-31 14:07 UTC, SytseGroenwold commented on docs/playbooks/asreview.md
> +# Playbook <name>
Test.

2022-03-31 14:09 UTC, tsmeele commented on docs/playbooks/asreview.md
> +# Playbook <name>
```suggestion
# Playbook ASReview
```

2022-04-29 10:44 UTC, tsmeele approved these changes

2022-05-03 10:55 UTC, J535D165 approved these changes

2022-05-03 12:48 UTC, merged